# Generated by Django 5.0.6 on 2024-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_caso', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
